function getRecommendedActions(risk) {
  if (risk === "HIGH") {
    return `
      🚨 Immediate Actions:
      <ul>
        <li>Implement emergency irrigation planning</li>
        <li>Deploy heat-resistant crop varieties</li>
        <li>Issue climate risk advisories to farmers</li>
      </ul>
    `;
  }

  if (risk === "MEDIUM") {
    return `
      ⚠️ Preventive Actions:
      <ul>
        <li>Optimize water usage</li>
        <li>Monitor crop stress weekly</li>
        <li>Prepare adaptive farming strategies</li>
      </ul>
    `;
  }

  return `
    ✅ Sustainable State:
    <ul>
      <li>Maintain current agricultural practices</li>
      <li>Continue climate monitoring</li>
      <li>Invest in long-term sustainability</li>
    </ul>
  `;
}

function runSimulation() {
  const temperature = document.getElementById("temperature").value;
  const rainfall = document.getElementById("rainfall").value;

  fetch("http://127.0.0.1:5000/simulate", {
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      temperature: temperature,
      rainfall: rainfall
    })
  })
  .then(response => response.json())
  .then(data => {
    window.latestSimulationData = {
  temperature_change: data.temperature_change,
  rainfall_change: data.rainfall_change,
  risk_level: data.risk_level,
  risk_score: data.risk_score,
  impacts: data.impacts,
  ai_explanation: data.ai_explanation,
  recommended_actions:getRecommendedActions(risk) 
};

function getRecommendedActions(risk) {
  if (risk === "HIGH") {
    return "Immediate actions required:\n- Emergency irrigation planning\n- Heat-resistant crop deployment\n- Climate risk advisories for farmers";
  }

  if (risk === "MEDIUM") {
    return "Preventive actions advised:\n- Optimize water usage\n- Monitor crop stress\n- Prepare adaptive strategies";
  }

  return "Current state is stable:\n- Maintain practices\n- Continue monitoring\n- Invest in sustainability";
}
    document.getElementById("result").style.display = "block";
  document.getElementById("risk").innerHTML = `
  <span class="${data.risk_level}">
    <strong>Risk Level:</strong> ${data.risk_level}
  </span><br>
  <strong>Risk Score:</strong> ${data.risk_score}<br>
  <strong>Temperature Change:</strong> ${data.temperature_change} °C<br>
  <strong>Rainfall Change:</strong> ${data.rainfall_change} %
`;


    document.getElementById("impacts").innerHTML =
      `<strong>Impacts:</strong><br>• ${data.impacts.join("<br>• ")}`;

    document.getElementById("ai").innerHTML =
      `<strong>AI Insight:</strong> ${data.ai_explanation}`;
      saveRiskForMap(data.risk_level);
      document.getElementById("actions").innerHTML =
  `<strong>Recommended Actions:</strong>${getRecommendedActions(data.risk_level)}`;


  })
  .catch(error => {
    alert("Backend not running. Please start Flask server.");
    console.error(error);
  });
}
// Save risk to localStorage for map page
function saveRiskForMap(risk) {
  localStorage.setItem("orbitEdRisk", risk);
}
function downloadReport() {
  if (!window.latestSimulationData) {
    alert("Run a simulation first!");
    return;
  }

  const d = window.latestSimulationData;

  const reportText = `
ORBIT-ED | AI CLIMATE INTELLIGENCE REPORT
---------------------------------------

Simulation Summary:
Temperature Change : ${d.temperature_change} °C
Rainfall Change    : ${d.rainfall_change} %

Risk Assessment:
Risk Level : ${d.risk_level}
Risk Score : ${d.risk_score}

Identified Impacts:
${d.impacts.map(i => "- " + i).join("\n")}

AI Explanation:
${d.ai_explanation}

Recommended Actions:
${d.recommended_actions}

Generated by Orbit-Ed
Space Intelligence for Earth
  `;

  const blob = new Blob([reportText], { type: "text/plain" });
  const url = URL.createObjectURL(blob);

  const a = document.createElement("a");
  a.href = url;
  a.download = "OrbitEd_AI_Report.txt";
  a.click();

  URL.revokeObjectURL(url);
}
